### ISSUE TITLE
i want you to add button to fix the car and heal like F3 to noclip

### ISSUE THREAD

**Issue by Saudx1** [Joeyarrabi/skidmenu#10]
Hey 
can you add button to repair the car and another button to heal like F3 noclip 
and more things on all players troll

**Comment by Joeyarrabi** [comment]
I can make it something configurable (the top of the menu's source code) and also add a keybindings menu in the misc menu.  Great idea!  I'll update you here once I've added it.

**Comment by Saudx1** [comment]
okay thanks ❤

**Comment by Joeyarrabi** [comment]
Added, sorry for the long wait!  Please open a new issue if you have any more suggestions.
