### ISSUE TITLE
Everyone?

### ISSUE THREAD

**Issue by Kawan** [Joeyarrabi/skidmenu#17]
Is it possible to make this menu accessible only for admin or owner?

**Comment by XvenDeR** [comment]
yes.

**Comment by Kawan** [comment]
Could you tell me how? I couldn't find it in cofig section

**Comment by Joeyarrabi** [comment]
It is possible, but would require some editing.  This menu wasn't designed for server administration however.  If you want a good menu for your server, I would recommend [vMenu](https://github.com/TomGrobbe/vMenu/releases/tag/v3.2.1).
