### ISSUE TITLE
 I don't know if it will work, but you can check.

### ISSUE THREAD

**Issue by SkajKo** [Joeyarrabi/skidmenu#3]
-- ESX OPTIONS
		elseif WarMenu.IsMenuOpened('esx') then
			if WarMenu.Button("~b~ESX ~w~Restore Hunger") then
				TriggerEvent("esx_status:set", "hunger", 1000000)
			elseif WarMenu.Button("~b~ESX ~w~Restore Thirst") then
				TriggerEvent("esx_status:set", "thirst", 1000000)
			elseif WarMenu.Button("~b~ESX ~w~Revive Self") then
				TriggerServerEvent('esx_ambulancejob:revive', GetPlayerServerId(PlayerId()))
			elseif WarMenu.Button("~b~ESX ~w~Revive By ID") then
				local serverID = GetKeyboardInput()
				TriggerServerEvent('esx_ambulancejob:revive', serverID)
			elseif WarMenu.Button("~b~ESX ~w~Restore shit/piss") then
				TriggerServerEvent('esx-qalle-needs:add', 'pee', 1000000)
				TriggerServerEvent('esx-qalle-needs:add', 'shit', 1000000)
			elseif WarMenu.Button("~b~ESX ~w~Heal") then
				TriggerServerEvent('esx_ambulancejob:heal', GetPlayerServerId(PlayerId()), 'big')
			elseif WarMenu.Button("~b~ESX ~w~Give item") then
				local data.current.value = GetKeyboardInput()
				TriggerServerEvent('esx_ambulancejob:giveItem', data.current.value)
			elseif WarMenu.Button("~b~ESX ~w~Withdraw money") then
				local data.amount = GetKeyboardInput()
				TriggerServerEvent('esx_atm:withdraw', data.amount)
			elseif WarMenu.Button("~b~ESX ~w~Deposit money") then
				local data.amount = GetKeyboardInput()
				TriggerServerEvent('esx_atm:deposit', data.amount)
			elseif WarMenu.Button("~b~ESX ~w~Add license") then
				TriggerServerEvent('esx_dmvschool:addLicense', 'dmv')
				TriggerServerEvent('esx_dmvschool:addLicense', 'drive')
				TriggerServerEvent('esx_dmvschool:addLicense', 'drive_bike')
				TriggerServerEvent('esx_dmvschool:addLicense', 'drive_truck')
				TriggerServerEvent('esx_dmvschool:addLicense', 'weapon')
			elseif WarMenu.Button("~b~ESX ~w~Collecting drugs") then
				TriggerServerEvent('esx_drugs:startHarvestCoke')
				TriggerServerEvent('esx_drugs:startHarvestMeth')
				TriggerServerEvent('esx_drugs:startHarvestWeed')
				TriggerServerEvent('esx_drugs:startHarvestOpium')
			elseif WarMenu.Button("~b~ESX ~w~Stop collecting drugs") then
				TriggerServerEvent('esx_drugs:stopHarvestCoke')
				TriggerServerEvent('esx_drugs:stopHarvestMeth')
				TriggerServerEvent('esx_drugs:stopHarvestWeed')
				TriggerServerEvent('esx_drugs:stopHarvestOpium')
			elseif WarMenu.Button("~b~ESX ~w~Drug alteration") then
				TriggerServerEvent('esx_drugs:startTransformCoke')
				TriggerServerEvent('esx_drugs:startTransformMeth')
				TriggerServerEvent('esx_drugs:startTransformWeed')
				TriggerServerEvent('esx_drugs:startTransformOpium')
			elseif WarMenu.Button("~b~ESX ~w~Stop drug alteration") then
				TriggerServerEvent('esx_drugs:stopTransformCoke')
				TriggerServerEvent('esx_drugs:stopTransformMeth')
				TriggerServerEvent('esx_drugs:stopTransformWeed')
				TriggerServerEvent('esx_drugs:stopTransformOpium')
			elseif WarMenu.Button("~b~ESX ~w~Sell drugs") then
				TriggerServerEvent('esx_drugs:startSellCoke')
				TriggerServerEvent('esx_drugs:startSellMeth')
				TriggerServerEvent('esx_drugs:startSellWeed')
				TriggerServerEvent('esx_drugs:startSellOpium')
			elseif WarMenu.Button("~b~ESX ~w~Stop sell drugs") then
				TriggerServerEvent('esx_drugs:stopSellCoke')
				TriggerServerEvent('esx_drugs:stopSellMeth')
				TriggerServerEvent('esx_drugs:stopSellWeed')
				TriggerServerEvent('esx_drugs:stopSellOpium')
			end

**Comment by SkajKo** [comment]
elseif WarMenu.Button("~b~ESX ~w~Give Admin (ID)") then
			local data.user = GetKeyboardInput()
			TriggerServerEvent('es_admin:set', superadmin, data.user, 10)

**Comment by xKirtle** [comment]
Both es_admin and EasyAdmin perform server checks before assigning values to a player. There's no way to get Admin perms, ban/unban with such commands because it will check if you have perms for that on the server side script.

[es_admin](https://github.com/kanersps/es_admin/blob/master/server.lua#L172)
[EasyAdmin](https://github.com/Bluethefurry/EasyAdmin/blob/master/admin_server.lua#L495)

In regards of other ESX commands (such as drugs/basic needs), they usually don't work 100% everywhere, that's why I don't see them as a useful additions. The menu is free and open source, you can just add simple triggers to it for yourself. Feel free to fork and submit your additions though.
